"""Style constants for HackAttack widgets."""

from .dashboard import (
    DASHBOARD_HEADER_TITLE_STYLE,
    DASHBOARD_REFRESH_BUTTON_STYLE,
    DASHBOARD_CARD_STYLE,
    DASHBOARD_VALUE_STYLE,
    DASHBOARD_NAME_STYLE,
    DASHBOARD_DETAIL_STYLE,
    DASHBOARD_STATUS_CARD_TEMPLATE,
    DASHBOARD_STATUS_TITLE_STYLE,
    DASHBOARD_STATUS_NAME_STYLE,
    DASHBOARD_STATUS_STATE_STYLE,
    DASHBOARD_ACTIVITY_LIST_STYLE,
)
from .placeholders import (
    PLACEHOLDER_ICON_STYLE,
    PLACEHOLDER_DESCRIPTION_CARD_STYLE,
    PLACEHOLDER_DESCRIPTION_TEXT_STYLE,
    PLACEHOLDER_MISSING_STYLE,
)

__all__ = [
    "DASHBOARD_HEADER_TITLE_STYLE",
    "DASHBOARD_REFRESH_BUTTON_STYLE",
    "DASHBOARD_CARD_STYLE",
    "DASHBOARD_VALUE_STYLE",
    "DASHBOARD_NAME_STYLE",
    "DASHBOARD_DETAIL_STYLE",
    "DASHBOARD_STATUS_CARD_TEMPLATE",
    "DASHBOARD_STATUS_TITLE_STYLE",
    "DASHBOARD_STATUS_NAME_STYLE",
    "DASHBOARD_STATUS_STATE_STYLE",
    "DASHBOARD_ACTIVITY_LIST_STYLE",
    "PLACEHOLDER_ICON_STYLE",
    "PLACEHOLDER_DESCRIPTION_CARD_STYLE",
    "PLACEHOLDER_DESCRIPTION_TEXT_STYLE",
    "PLACEHOLDER_MISSING_STYLE",
]
