"""
Security & Compliance tab for BLACKSTORM - Security and compliance tools.
"""
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, 
    QListWidget, QListWidgetItem, QGroupBox, QTextEdit,
    QFormLayout, QLineEdit, QFileDialog, QTabWidget, QProgressBar,
    QMessageBox, QComboBox, QCheckBox, QSplitter, QTableWidget,
    QTableWidgetItem, QHeaderView, QTreeWidget, QTreeWidgetItem, QSpinBox
)
from PySide6.QtCore import Qt, Signal

class SecurityComplianceTab(QWidget):
    """Tab for security and compliance features."""
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setup_ui()
    
    def setup_ui(self):
        """Set up the user interface."""
        layout = QVBoxLayout(self)
        
        # Main content with tabs
        tabs = QTabWidget()
        
        # Compliance Reports tab
        reports_tab = QWidget()
        self.setup_reports_tab(reports_tab)
        tabs.addTab(reports_tab, "Compliance Reports")
        
        # Audit Log tab
        audit_tab = QWidget()
        self.setup_audit_tab(audit_tab)
        tabs.addTab(audit_tab, "Audit Log")
        
        # Security Settings tab
        settings_tab = QWidget()
        self.setup_settings_tab(settings_tab)
        tabs.addTab(settings_tab, "Security Settings")
        
        # Add tabs to layout
        layout.addWidget(tabs)
    
    def setup_reports_tab(self, parent):
        """Set up the Compliance Reports tab."""
        layout = QVBoxLayout(parent)
        
        # Toolbar
        toolbar = QHBoxLayout()
        
        btn_generate = QPushButton("Generate Report")
        btn_export = QPushButton("Export Report")
        btn_print = QPushButton("Print")
        
        # Style buttons
        for btn in [btn_generate, btn_export, btn_print]:
            btn.setStyleSheet("""
                QPushButton {
                    padding: 5px 10px;
                    border: 1px solid #3E3E3E;
                    border-radius: 4px;
                    background: #2A2D2E;
                    color: #E0E0E0;
                }
                QPushButton:hover {
                    background: #3E3E3E;
                }
            """)
        
        toolbar.addWidget(btn_generate)
        toolbar.addWidget(btn_export)
        toolbar.addWidget(btn_print)
        toolbar.addStretch()
        
        # Report type selection
        report_layout = QHBoxLayout()
        report_layout.addWidget(QLabel("Report Type:"))
        
        self.report_type = QComboBox()
        self.report_type.addItems([
            "Wipe Certification",
            "Compliance Summary",
            "Device Inventory",
            "Security Audit"
        ])
        
        report_layout.addWidget(self.report_type)
        report_layout.addStretch()
        
        # Report content
        self.report_content = QTextEdit()
        self.report_content.setReadOnly(True)
        self.report_content.setStyleSheet("""
            QTextEdit {
                background: #2A2D2E;
                color: #E0E0E0;
                border: 1px solid #3E3E3E;
                border-radius: 4px;
                font-family: monospace;
            }
        """)
        
        # Add sample report content
        self.report_content.setPlainText(
            "=== WIPE CERTIFICATION REPORT ===\n\n"
            "Date: 2025-06-04 14:30:00\n"
            "Generated by: Admin\n\n"
            "DEVICE INFORMATION\n"
            "------------------\n"
            "Device: /dev/sda\n"
            "Model: Samsung SSD 860 EVO 500GB\n"
            "Serial: S3Z8NB0K123456\n"
            "Capacity: 465.8 GB\n\n"
            "WIPE DETAILS\n"
            "------------\n"
            "Method: DoD 5220.22-M (3-pass)\n"
            "Start Time: 2025-06-04 14:00:00\n"
            "End Time: 2025-06-04 14:25:30\n"
            "Status: COMPLETED\n\n"
            "VERIFICATION\n"
            "-----------\n"
            "Verification Method: Full read\n"
            "Verification Status: PASSED\n"
            "All sectors verified as wiped\n\n"
            "CERTIFICATION\n"
            "------------\n"
            "This certifies that the device has been securely wiped\n"
            "in accordance with the selected standard. No recoverable\n"
            "data remains on the device.\n\n"
            "Signed:\n"
            "BLACKSTORM Secure Erasure System\n"
            "https://blackstorm.example.com"
        )
        
        # Add to layout
        layout.addLayout(toolbar)
        layout.addLayout(report_layout)
        layout.addWidget(self.report_content)
        
        # Connect signals
        btn_generate.clicked.connect(self.generate_report)
        btn_export.clicked.connect(self.export_report)
        btn_print.clicked.connect(self.print_report)
    
    def setup_audit_tab(self, parent):
        """Set up the Audit Log tab."""
        layout = QVBoxLayout(parent)
        
        # Toolbar
        toolbar = QHBoxLayout()
        
        btn_refresh = QPushButton("Refresh")
        btn_export = QPushButton("Export Log")
        btn_clear = QPushButton("Clear Log")
        
        # Style buttons
        for btn in [btn_refresh, btn_export, btn_clear]:
            btn.setStyleSheet("""
                QPushButton {
                    padding: 5px 10px;
                    border: 1px solid #3E3E3E;
                    border-radius: 4px;
                    background: #2A2D2E;
                    color: #E0E0E0;
                }
                QPushButton:hover {
                    background: #3E3E3E;
                }
            """)
        
        toolbar.addWidget(btn_refresh)
        toolbar.addWidget(btn_export)
        toolbar.addWidget(btn_clear)
        toolbar.addStretch()
        
        # Filter controls
        filter_layout = QHBoxLayout()
        filter_layout.addWidget(QLabel("Filter:"))
        
        self.filter_type = QComboBox()
        self.filter_type.addItems([
            "All Events",
            "Wipe Operations",
            "Login Attempts",
            "System Events",
            "Security Events"
        ])
        
        filter_layout.addWidget(self.filter_type)
        filter_layout.addStretch()
        
        # Audit log table
        self.audit_table = QTableWidget()
        self.audit_table.setColumnCount(5)
        self.audit_table.setHorizontalHeaderLabels([
            "Timestamp", "Event Type", "User", "Device", "Details"
        ])
        
        # Style table
        self.audit_table.setStyleSheet("""
            QTableWidget {
                background: #2A2D2E;
                color: #E0E0E0;
                border: 1px solid #3E3E3E;
                border-radius: 4px;
                gridline-color: #3E3E3E;
            }
            QHeaderView::section {
                background: #2A2D2E;
                color: #B0B0B0;
                padding: 5px;
                border: none;
                border-right: 1px solid #3E3E3E;
                border-bottom: 1px solid #3E3E3E;
            }
            QTableWidget::item {
                padding: 5px;
                border-bottom: 1px solid #3E3E3E;
            }
            QTableWidget::item:selected {
                background: #3E3E3E;
                color: white;
            }
        """)
        
        # Configure table properties
        self.audit_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.audit_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
        self.audit_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.audit_table.setSortingEnabled(True)
        
        # Set column widths
        header = self.audit_table.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)  # Timestamp
        header.setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)  # Event Type
        header.setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)  # User
        header.setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)  # Device
        header.setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)  # Details
        
        # Add sample audit log entries
        self.add_sample_audit_entries()
        
        # Add to layout
        layout.addLayout(toolbar)
        layout.addLayout(filter_layout)
        layout.addWidget(self.audit_table)
        
        # Connect signals
        btn_refresh.clicked.connect(self.refresh_audit_log)
        btn_export.clicked.connect(self.export_audit_log)
        btn_clear.clicked.connect(self.clear_audit_log)
        self.filter_type.currentIndexChanged.connect(self.filter_audit_log)
    
    def setup_settings_tab(self, parent):
        """Set up the Security Settings tab."""
        layout = QVBoxLayout(parent)
        
        # Security settings group
        settings_group = QGroupBox("Security Settings")
        settings_layout = QFormLayout()
        
        # Password protection
        self.enable_password = QCheckBox("Enable password protection")
        
        # Auto-lock
        self.auto_lock = QCheckBox("Auto-lock after period of inactivity")
        self.lock_timeout = QSpinBox()
        self.lock_timeout.setRange(1, 120)
        self.lock_timeout.setValue(15)
        self.lock_timeout.setSuffix(" minutes")
        
        # Audit logging
        self.enable_audit = QCheckBox("Enable audit logging")
        self.log_retention = QSpinBox()
        self.log_retention.setRange(1, 365)
        self.log_retention.setValue(30)
        self.log_retention.setSuffix(" days")
        
        # Add to form
        settings_layout.addRow(self.enable_password)
        settings_layout.addRow(self.auto_lock)
        settings_layout.addRow("Inactivity timeout:", self.lock_timeout)
        settings_layout.addRow(self.enable_audit)
        settings_layout.addRow("Log retention period:", self.log_retention)
        
        # Save button
        btn_save = QPushButton("Save Settings")
        btn_save.clicked.connect(self.save_security_settings)
        
        settings_layout.addRow(btn_save)
        settings_group.setLayout(settings_layout)
        
        # Add to layout
        layout.addWidget(settings_group)
        layout.addStretch()
        
        # Load current settings
        self.load_security_settings()
    
    def generate_report(self):
        """Generate a compliance report."""
        report_type = self.report_type.currentText()
        QMessageBox.information(self, "Report Generated", 
                              f"{report_type} report generated successfully.")
    
    def export_report(self):
        """Export the current report to a file."""
        file_name, _ = QFileDialog.getSaveFileName(
            self, "Export Report", "", "PDF Files (*.pdf);;Text Files (*.txt)"
        )
        
        if file_name:
            QMessageBox.information(self, "Export Successful", 
                                  f"Report exported to {file_name}")
    
    def print_report(self):
        """Print the current report."""
        QMessageBox.information(self, "Print", "Printing report...")
    
    def add_sample_audit_entries(self):
        """Add sample entries to the audit log."""
        entries = [
            ["2025-06-04 14:30:00", "Wipe", "admin", 
             "/dev/sdb", "Wipe completed (DoD 5220.22-M, 3-pass)"],
            ["2025-06-04 14:25:15", "Wipe", "admin", 
             "/dev/sdb", "Wipe started (DoD 5220.22-M, 3-pass)"],
            ["2025-06-04 14:20:30", "Login", "admin", 
             "-", "User logged in from 192.168.1.100"],
            ["2025-06-04 14:15:45", "System", "-", 
             "-", "System started"],
            ["2025-06-03 09:45:22", "Wipe", "admin", 
             "/dev/sda", "Wipe verified (100.0%)"],
        ]
        
        self.audit_table.setRowCount(len(entries))
        
        for row, entry in enumerate(entries):
            for col, value in enumerate(entry):
                item = QTableWidgetItem(value)
                self.audit_table.setItem(row, col, item)
    
    def refresh_audit_log(self):
        """Refresh the audit log display."""
        # In a real app, this would reload the log from disk/database
        QMessageBox.information(self, "Refresh", "Audit log refreshed.")
    
    def export_audit_log(self):
        """Export the audit log to a file."""
        file_name, _ = QFileDialog.getSaveFileName(
            self, "Export Audit Log", "", "CSV Files (*.csv);;Text Files (*.txt)"
        )
        
        if file_name:
            QMessageBox.information(self, "Export Successful", 
                                  f"Audit log exported to {file_name}")
    
    def clear_audit_log(self):
        """Clear the audit log."""
        reply = QMessageBox.question(
            self, "Clear Audit Log", 
            "Are you sure you want to clear the audit log? This cannot be undone.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )
        
        if reply == QMessageBox.StandardButton.Yes:
            self.audit_table.setRowCount(0)
    
    def filter_audit_log(self):
        """Filter the audit log by event type."""
        # In a real app, this would filter the log entries
        filter_text = self.filter_type.currentText()
        QMessageBox.information(self, "Filter", f"Filtering by: {filter_text}")
    
    def load_security_settings(self):
        """Load security settings from configuration."""
        # In a real app, this would load from a config file/database
        self.enable_password.setChecked(True)
        self.auto_lock.setChecked(True)
        self.lock_timeout.setValue(15)
        self.enable_audit.setChecked(True)
        self.log_retention.setValue(30)
    
    def save_security_settings(self):
        """Save security settings to configuration."""
        # In a real app, this would save to a config file/database
        QMessageBox.information(self, "Settings Saved", 
                              "Security settings have been saved.")
